SIM=verilator
TOPLEVEL_LANG = verilog
VERILOG_SOURCES = /home/zyy/coco_work/cocoTest/fdt_ctrl_re_re/rtl/*

TOPLEVEL = fdt_ctrl
MODULE = testbench
EXTRA_ARGS += --trace-fst --trace-structs --Wno-WIDTH -Wno-CMPCONST

include $(shell cocotb-config --makefiles)/Makefile.sim